# name: Rbank dapp build and deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build_and_deploy:
    
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Setup Node 12
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12'

#     - name: Cache dependencies
#       uses: actions/cache@v2
#       id: cache
#       with:
#         path: ~/.npm
#         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#         restore-keys: |
#           ${{ runner.os }}-node-

#     - name: Install dependencies
#       run: npm ci

#     - name: Build site
#       env:
#         VUE_APP_NETWORK_ID: ${{ secrets.TESTNET_VUE_APP_NETWORK_ID }}
#         VUE_APP_WS_PROVIDER: ${{ secrets.TESTNET_VUE_APP_WS_PROVIDER }}
#         VUE_APP_RBANK_CONTROLLER: ${{ secrets.TESTNET_VUE_APP_RBANK_CONTROLLER }}
#       run: npm run build

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.TESTNET_AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.TESTNET_AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.TESTNET_AWS_REGION }}

#     - name: Deploy site to S3
#       run: |
#         aws s3 sync --delete --only-show-errors dist/ ${{ secrets.TESTNET_S3_BUCKET }}

#     - name: Invalidate CloudFront cache
#       run: |
#         aws cloudfront create-invalidation --distribution-id ${{ secrets.TESTNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
